title: Michelle Tran # your name (or website title) here
logo: "/images/IMG_4049.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Intro to Computational Foundations
  <br><br>
  Portfolio Extra Credit
  <br><br>
  <a href="https://www.linkedin.com/in/michelletran03/">View My LinkedIn Profile</a>
  <br><br>
   <a href="https://github.com/michellio/portfolio2020">View My Portfolio</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
